# Generated by Django 4.2.7 on 2024-03-13 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_clientemodel_fantasia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=50)),
                ('valor_do_produton', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PedidosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.clientemodel')),
            ],
        ),
    ]
