# Generated by Django 4.2.7 on 2024-03-13 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_clientes', '0002_rename_valor_do_produton_produtosmodel_valor_do_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtosmodel',
            name='valor_do_produto',
        ),
    ]
