# Generated by Django 4.2.7 on 2024-03-13 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_clientes', '0003_remove_produtosmodel_valor_do_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedidoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='pedido_clientes.pedidosmodel')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_produto', to='pedido_clientes.produtosmodel')),
            ],
        ),
    ]
