# Generated by Django 4.2.7 on 2024-03-13 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_clientes', '0004_itempedidomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosmodel',
            name='data_pedido',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
