# Generated by Django 4.2.7 on 2024-03-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_clientes', '0005_pedidosmodel_data_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedidomodel',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
