# Generated by Django 4.2.7 on 2024-03-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_clientes', '0006_alter_itempedidomodel_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedidomodel',
            name='referencia',
            field=models.CharField(choices=[('caixa', 'Caixa'), ('kilo', 'Quilo')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
