# Generated by Django 4.2.7 on 2024-03-13 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_clientemodel_fantasia'),
        ('pedido_clientes', '0007_itempedidomodel_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidosmodel',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientemodel'),
        ),
    ]
