# Generated by Django 4.2.7 on 2024-03-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_clientes', '0008_alter_pedidosmodel_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedidomodel',
            name='referencia',
            field=models.CharField(choices=[('caixa', 'Caixa'), ('quilo', 'Quilo'), ('quilo', 'Unidade')], max_length=10),
        ),
    ]
