# Generated by Django 4.2.7 on 2024-03-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_clientes', '0009_alter_itempedidomodel_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedidomodel',
            name='referencia',
            field=models.CharField(choices=[('caixa', 'Caixa'), ('quilo', 'Quilo'), ('quilo', 'Unidade'), ('fardo', 'Fardo')], max_length=10),
        ),
    ]
