# Generated by Django 4.2.4 on 2024-03-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_clientes', '0010_alter_itempedidomodel_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedidomodel',
            name='quantidade',
            field=models.ImageField(upload_to=''),
        ),
    ]
