# Generated by Django 4.2.4 on 2024-03-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_clientes', '0012_alter_itempedidomodel_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedidomodel',
            name='referencia',
            field=models.CharField(choices=[('caixa', 'Cx'), ('quilo', 'Kg'), ('quilo', 'UN'), ('fardo', 'FD')], max_length=10),
        ),
    ]
