# Generated by Django 4.2.7 on 2024-03-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemodel',
            name='telefone',
            field=models.IntegerField(default=98988441478),
            preserve_default=False,
        ),
    ]
