# Generated by Django 4.2.7 on 2024-03-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clientemodel_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemodel',
            name='fantasia',
            field=models.CharField(default='taylon', max_length=50),
            preserve_default=False,
        ),
    ]
